version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: ss-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-security
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
